/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos (v0.1.56), and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 George MacKerron
Released under the MIT licence: see LICENCE file
*/

import type {
  JSONValue,
  JSONArray,
  DateString,
  SQLFragment,
  SQL,
  GenericSQLExpression,
  ColumnNames,
  ColumnValues,
  Parameter,
  ParentColumn,
  DefaultType,
} from './src/core';


/* === schema: public === */

/* --- enums --- */

export type stock_option = 'No' | 'Yes';
export declare namespace every {
  export type stock_option = ['No', 'Yes'];
}

/* --- tables --- */

export declare namespace recall {
  export type Table = 'recall';
  export interface Selectable {
    id: number;
    date: Date;
    drug: string;
    mfgr: string;
    lot: string;
    stocked: stock_option;
    affected: stock_option;
    date_removed: Date;
    initials: string;
  }
  export interface Insertable {
    id?: number | Parameter<number> | DefaultType | SQLFragment;
    date: Date | Parameter<Date> | DateString | SQLFragment;
    drug: string | Parameter<string> | SQLFragment;
    mfgr: string | Parameter<string> | SQLFragment;
    lot: string | Parameter<string> | SQLFragment;
    stocked: stock_option | Parameter<stock_option> | SQLFragment;
    affected: stock_option | Parameter<stock_option> | SQLFragment;
    date_removed: Date | Parameter<Date> | DateString | SQLFragment;
    initials: string | Parameter<string> | SQLFragment;
  }
  export interface Updatable extends Partial<Insertable> { }
  export type Whereable = { [K in keyof Insertable]?: Exclude<Insertable[K] | ParentColumn, null | DefaultType> };
  export type JSONSelectable = { [K in keyof Selectable]:
    Date extends Selectable[K] ? Exclude<Selectable[K], Date> | DateString :
    Date[] extends Selectable[K] ? Exclude<Selectable[K], Date[]> | DateString[] :
    Selectable[K]
  };
  export type UniqueIndex = 'recall_pkey';
  export type Column = keyof Selectable;
  export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
  export type SQLExpression = GenericSQLExpression | Table | Whereable | Column | ColumnNames<Updatable | (keyof Updatable)[]> | ColumnValues<Updatable>;
  export type SQL = SQLExpression | SQLExpression[];
}

/* === cross-table types === */

export type Table = recall.Table;
export type Selectable = recall.Selectable;
export type Whereable = recall.Whereable;
export type Insertable = recall.Insertable;
export type Updatable = recall.Updatable;
export type UniqueIndex = recall.UniqueIndex;
export type Column = recall.Column;
export type AllTables = [recall.Table];


export type SelectableForTable<T extends Table> = {
  recall: recall.Selectable;
}[T];

export type WhereableForTable<T extends Table> = {
  recall: recall.Whereable;
}[T];

export type InsertableForTable<T extends Table> = {
  recall: recall.Insertable;
}[T];

export type UpdatableForTable<T extends Table> = {
  recall: recall.Updatable;
}[T];

export type UniqueIndexForTable<T extends Table> = {
  recall: recall.UniqueIndex;
}[T];

export type ColumnForTable<T extends Table> = {
  recall: recall.Column;
}[T];

export type SQLForTable<T extends Table> = {
  recall: recall.SQL;
}[T];

